set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
run '~/.tmux/plugins/tpm/tpm'

set -g prefix C-t

bind m split-window -h
bind n split-window -v

bind q kill-pane

set-option -g mouse on
set-option -g status-position top
set-option -g detach-on-destroy on
set -g @catppuccin_flavour "mocha"
