[colors.primary]
background = "#0f0f0f"

[font]
size = 12
[font.normal]
family = "JetBrains Mono"
style = "Regular"
[font.bold]
family = "JetBrains Mono"
style = "Bold"
[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"
[font.italic]
family = "JetBrains Mono"
style = "Italic"
