require("configs")
require("keymaps")

require("plugins")
require("plugins.borders")
require("plugins.cmp")
require("plugins.format")
require("plugins.lsp")
require("plugins.mason")
require("plugins.nvim-ts")
